/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import VISTA.JFrame_Contenedor;
import MODELO.Class_Inicio_Usuarios;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author JHON SANCHEZ YEISON NORIEGA ADSI 600128
 */
public class JFrame_InicioUsuario extends javax.swing.JFrame {
	CONTROLADOR.Class_CONEXION conn = new CONTROLADOR.Class_CONEXION();// INSTANCIAR

	Class_Inicio_Usuarios obj = new Class_Inicio_Usuarios();

	/**
	 * Creates new form JFrame_Menu
	 */
	public JFrame_InicioUsuario() {

		initComponents();
		this.setLocationRelativeTo(null);
		Txt_Usuario.grabFocus();

//      this.setExtendedState(JFrame_Menu.MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Txt_Usuario = new javax.swing.JTextField();
		Txt_Password = new javax.swing.JPasswordField();
		Btt_Ingreso = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		Imagen = new javax.swing.JLabel();
		Btt_Ingreso1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Login"); // NOI18N
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
		setName("Login"); // NOI18N
		setType(java.awt.Window.Type.POPUP);

		Txt_Usuario.setMinimumSize(new java.awt.Dimension(6, 27));
		Txt_Usuario.setPreferredSize(new java.awt.Dimension(6, 27));
		Txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_UsuarioActionPerformed(evt);
			}
		});

		Txt_Password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_PasswordActionPerformed(evt);
			}
		});

		Btt_Ingreso.setBackground(new java.awt.Color(255, 102, 0));
		Btt_Ingreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		Btt_Ingreso.setText("Ingreso");
		Btt_Ingreso.setAutoscrolls(true);
		Btt_Ingreso.setPreferredSize(new java.awt.Dimension(64, 33));
		Btt_Ingreso.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btt_IngresoActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel2.setText("Contraseña");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel1.setText("Usuario");

		Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/Prorigger Garage Ambar50_.png"))); // NOI18N

		Btt_Ingreso1.setBackground(new java.awt.Color(255, 102, 0));
		Btt_Ingreso1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		Btt_Ingreso1.setText("Configuración");
		Btt_Ingreso1.setAutoscrolls(true);
		Btt_Ingreso1.setPreferredSize(new java.awt.Dimension(64, 33));
		Btt_Ingreso1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btt_Ingreso1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(101, 101, 101)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 284,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(42, 42, 42)
										.addComponent(Txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup()
												.addComponent(Btt_Ingreso1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGap(42, 42, 42).addComponent(Btt_Ingreso,
														javax.swing.GroupLayout.PREFERRED_SIZE, 80,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
												.addGap(15, 15, 15)
												.addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
														javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addContainerGap(92, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(23, 23, 23)
				.addComponent(
						Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(54, 54, 54)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel1))
						.addComponent(Txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(11, 11, 11)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel2))
						.addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(20, 20, 20)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(Btt_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(Btt_Ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(39, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void Btt_IngresoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Btt_IngresoActionPerformed

		this.Inicio_sesion("");
	}// GEN-LAST:event_Btt_IngresoActionPerformed

	private void Txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_PasswordActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_PasswordActionPerformed

	private void Txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_UsuarioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_UsuarioActionPerformed

	private void Btt_Ingreso1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Btt_Ingreso1ActionPerformed
		JFormConfig fr = new JFormConfig();
		fr.show();
		this.dispose();

// TODO add your handling code here:
	}// GEN-LAST:event_Btt_Ingreso1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrame_InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrame_InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrame_InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrame_InicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFrame_InicioUsuario().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Btt_Ingreso;
	private javax.swing.JButton Btt_Ingreso1;
	private javax.swing.JLabel Imagen;
	private javax.swing.JPasswordField Txt_Password;
	private javax.swing.JTextField Txt_Usuario;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

	public void Inicio_sesion(String Usu_username) {
		String cap = "";
		String usu = "";
		if (Txt_Usuario.getText().isEmpty() && Txt_Password.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Ingrese el Usuario y la Contraseña", "Inicio de Sesion",
					JOptionPane.INFORMATION_MESSAGE);
			Txt_Usuario.grabFocus();
		} else {
			try {
				obj.inicio_sesion(Txt_Usuario.getText(), Txt_Password.getText());
				while (obj.datos.next()) {

					cap = obj.datos.getString("Usu_tipo");
					usu = obj.datos.getString("Usu_username");
				}
				if (cap.equals("ADMINISTRADOR")) {
					this.setVisible(false);
					JFrame_Contenedor ingreso = new JFrame_Contenedor(usu);
					ingreso.setVisible(true);
					// ingreso.pack();
					this.dispose();
				} else if (cap.equals("MECANICO")) {
					this.setVisible(false);
					JFrame_Contenedor2 ingres = new JFrame_Contenedor2(usu);
					ingres.setVisible(true);
					// ingres.pack();
					this.dispose();
				} else {
					JOptionPane.showMessageDialog(null, "Usuario no Autorizado", "Inicio de Sesión",
							JOptionPane.ERROR_MESSAGE);
				}

			} catch (Exception ex) {
				System.out.println("Error" + ex.getMessage());
			}
		}
	}

}
