/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Class_Reparacion;
import java.awt.event.KeyEvent;
//import static VISTA.JFrame_Diagnostico.fechaactual;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author JHON SANCHEZ
 *         YEISON NORIEGA 
 *         ADSI 600128
 */
public class JInternalFrame_Reparacion extends javax.swing.JInternalFrame {

    Class_Reparacion obj = new Class_Reparacion();
     public String datos_empleado, datos_ingreso,aux="NULL";
    
    /**
     * Creates new form JInternalFrame_Reparacion
     */
    public JInternalFrame_Reparacion() {
        initComponents();
        Txt_Id_Placa.enable(false);
        Txt_ValorServicio.enable(false);
        Txt_nomservi.enable(false);
        Combo_Id.addItem("Selecc");
        Combo_IdServicio.addItem("Selecc");
        this.LlenarComboIngreso();
        this.LlenarComboServicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Combo_Id = new javax.swing.JComboBox();
        Txt_Id_Placa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Combo_IdServicio = new javax.swing.JComboBox();
        Txt_ValorServicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Txt_nomservi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescrip = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Prorigger Garage Azul50_.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SELECCIONE LA PLACA");

        Combo_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_IdActionPerformed(evt);
            }
        });

        Txt_Id_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Id_PlacaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("SELECCIONE EL COSTO DEL  SERVICIO");

        Combo_IdServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_IdServicioActionPerformed(evt);
            }
        });

        Txt_ValorServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ValorServicioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descripcion de la Reparación");

        jButton1.setText("REGISTRAR REPARACIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        TextAreaDescrip.setColumns(20);
        TextAreaDescrip.setRows(5);
        TextAreaDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextAreaDescripKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TextAreaDescrip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Combo_IdServicio, 0, 61, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_ValorServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Txt_nomservi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Combo_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_Id_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Id_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_IdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_ValorServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_nomservi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Combo_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_IdActionPerformed
                if(obj.datos_ingreso!=null)
                {
                        this.mostrar_combo();
                    }
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_IdActionPerformed

    private void Txt_Id_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Id_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Id_PlacaActionPerformed

    private void Combo_IdServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_IdServicioActionPerformed
                if(obj.datos_empleado!=null)
                {
                        this.MostrarServicio();
            
                    }
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_IdServicioActionPerformed

    private void Txt_ValorServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ValorServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ValorServicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.GuardarReparacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextAreaDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextAreaDescripKeyTyped
       char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
        else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_TextAreaDescripKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_Id;
    private javax.swing.JComboBox Combo_IdServicio;
    private javax.swing.JTextArea TextAreaDescrip;
    private javax.swing.JTextField Txt_Id_Placa;
    private javax.swing.JTextField Txt_ValorServicio;
    private javax.swing.JTextField Txt_nomservi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void LlenarComboIngreso()
    {
        try
        { Combo_Id.removeAllItems();
             Combo_Id.addItem("Seleccione...");
           obj.listar_combo_ingreso();
            while (obj.datos_ingreso.next()) 
            {
                this.Combo_Id.addItem(obj.datos_ingreso.getString(1));
            }               
                
            }
        catch(Exception ex)
        {
             System.out.println("error al cargar los datos"+ex.getMessage());
        }
        }
    
    public void mostrar_combo()
    {
        try
        {
            obj.listar_id_ingreso(Integer.parseInt(Combo_Id.getSelectedItem().toString()));
            if(obj.datos_ingreso.next()==true)
            {
                Txt_Id_Placa.setText(obj.datos_ingreso.getString(2));
            }
        }
        catch(Exception ex)
        {
             System.out.println("error al cargar los datos"+ex.getMessage());
        }
    }
     
    public void LlenarComboServicio()
    {
        try
        {
            obj.listar_combo_Servicio();
            while (obj.datos_empleado.next())
            {
                this.Combo_IdServicio.addItem(obj.datos_empleado.getInt(1));
            }                
                
            }
        catch(Exception ex)
        {
            System.out.println("error al cargar los datos"+ex.getMessage());
        }
        }
    
    public void MostrarServicio()
    {
        try
        {
            obj.listar_id_Servicio(Integer.parseInt(Combo_IdServicio.getSelectedItem().toString()));
            //obj.listar_id_Servicio(Integer.parseInt(Combo_NombreServicio.getSelectedItem().toString()));
            if(obj.datos_empleado.next())
            {
                Txt_ValorServicio.setText(obj.datos_empleado.getString(3));
               Txt_nomservi.setText(obj.datos_empleado.getString(2));
            }
        }
        catch(Exception ex)
        {
            System.out.println("error al cargar los datos"+ex.getMessage());
        }
    }
    
    public void GuardarReparacion()
    {
        try
        {
            obj.Guardar(Integer.parseInt(Combo_Id.getSelectedItem().toString()), Integer.parseInt(Combo_IdServicio.getSelectedItem().toString()), Txt_Id_Placa.getText(), Double.parseDouble(Txt_ValorServicio.getText()), Txt_nomservi.getText(), TextAreaDescrip.getText());
            //obj.Guardar(Integer.parseInt(Combo_IdServicio.getSelectedItem().toString()), Txt_Id_Placa.getText(), Double.parseDouble(Txt_ValorServicio.getText()), Txt_nomservi.getText(), Txt_Descripcion.getText());
             JOptionPane.showMessageDialog(null,"El registro fue ingresado","REPARACIÓN", JOptionPane.INFORMATION_MESSAGE);
             this.Limpiar();
             LlenarComboIngreso();
        }
        catch(Exception ex)
        {
            System.out.println("Error al guardar"+ex.getMessage());
        }
    }
    
    public void Limpiar()
{
 
    Combo_Id.setSelectedItem("Selecc");
    Txt_Id_Placa.setText("");
    Combo_IdServicio.setSelectedItem("Selecc");
    Txt_ValorServicio.setText("");
    Txt_nomservi.setText("");
    TextAreaDescrip.setText("");
}
    
    }
    
    

