/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Class_Recepcion_Cliente;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author JHON SANCHEZ
 *         YEISON NORIEGA 
 *         ADSI 600128
 */
public class JInternalFrame_Cliente extends javax.swing.JInternalFrame {
    
    MODELO.Class_Recepcion_Cliente conn=new MODELO.Class_Recepcion_Cliente();
   Class_Recepcion_Cliente obj=new Class_Recepcion_Cliente();
   JTable modelo=new JTable();
   private String[] datos;

    /**
     * Creates new form JInternalFrame_Cliente
     */
    public JInternalFrame_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_Direccion = new javax.swing.JTextField();
        Txt_Ciudad = new javax.swing.JTextField();
        Txt_Telefono = new javax.swing.JTextField();
        Txt_Documento = new javax.swing.JTextField();
        Btt_Ingresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Btt_Limpiar = new javax.swing.JButton();
        Btt_Consultar = new javax.swing.JButton();
        Btt_Listar = new javax.swing.JButton();
        Btt_Eliminar = new javax.swing.JButton();
        Btt_Actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Lista = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setName("Clientes"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Direccion");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ciudad");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Documento");

        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyTyped(evt);
            }
        });

        Txt_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DireccionActionPerformed(evt);
            }
        });
        Txt_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DireccionKeyTyped(evt);
            }
        });

        Txt_Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CiudadActionPerformed(evt);
            }
        });
        Txt_Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_CiudadKeyTyped(evt);
            }
        });

        Txt_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoActionPerformed(evt);
            }
        });
        Txt_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_TelefonoKeyTyped(evt);
            }
        });

        Txt_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DocumentoActionPerformed(evt);
            }
        });
        Txt_Documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DocumentoKeyTyped(evt);
            }
        });

        Btt_Ingresar.setText("Ingresar");
        Btt_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_IngresarActionPerformed(evt);
            }
        });

        Btt_Limpiar.setText("Limpiar");
        Btt_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_LimpiarActionPerformed(evt);
            }
        });

        Btt_Consultar.setText("Consultar");
        Btt_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_ConsultarActionPerformed(evt);
            }
        });

        Btt_Listar.setText("Listar");
        Btt_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_ListarActionPerformed(evt);
            }
        });

        Btt_Eliminar.setText("Eliminar");
        Btt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_EliminarActionPerformed(evt);
            }
        });

        Btt_Actualizar.setText("Actualizar");
        Btt_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Txt_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btt_Consultar))
                        .addComponent(Txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btt_Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btt_Ingresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btt_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btt_Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btt_Listar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btt_Limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(Btt_Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(Btt_Actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(Btt_Listar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(Btt_Consultar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Txt_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(Txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Txt_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_Lista.setToolTipText("Lista");
        jScrollPane1.setViewportView(Tabla_Lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        if(Txt_Nombre.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Seleccione el registro a actualizar","Clientes",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void Txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyTyped
        char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        }       
          else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_Txt_NombreKeyTyped

    private void Txt_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DireccionActionPerformed
        if(Txt_Direccion.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Seleccione el registro a actualizar","Clientes",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Txt_DireccionActionPerformed

    private void Txt_CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CiudadActionPerformed
        if(Txt_Ciudad.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Seleccione el registro a actualizar","Clientes",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Txt_CiudadActionPerformed

    private void Txt_CiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_CiudadKeyTyped
        char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        }      
          else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_Txt_CiudadKeyTyped

    private void Txt_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoActionPerformed
        if(Txt_Telefono.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Seleccione el registro a actualizar","Clientes",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Txt_TelefonoActionPerformed

    private void Txt_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TelefonoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'){
            getToolkit().beep();
            evt.consume();//CODIGO PARAINGRESAR SOLO NUMEROS
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoKeyTyped

    private void Txt_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DocumentoActionPerformed
        if(Txt_Documento.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Seleccione el registro a actualizar","Clientes",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Txt_DocumentoActionPerformed

    private void Txt_DocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DocumentoKeyTyped

        char c = evt.getKeyChar();
        if(c<'0' || c>'9')
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO NUMEROS
        }
    }//GEN-LAST:event_Txt_DocumentoKeyTyped

    private void Btt_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_IngresarActionPerformed
        this.gurdar_datos_cliente();
    }//GEN-LAST:event_Btt_IngresarActionPerformed

    private void Btt_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_LimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_Btt_LimpiarActionPerformed

    private void Btt_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ConsultarActionPerformed
        this.buscar();
    }//GEN-LAST:event_Btt_ConsultarActionPerformed

    private void Btt_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ListarActionPerformed
        try {
            Object modelodatos[][]= new Object[0][0];
            Object titulos[]={"DOCUMENTO","NOMBRE","DIRECCIÓN","CIUDAD","TELEFONO"};
            obj.llenar_tabla();
            ResultSetMetaData rsMd=obj.rs.getMetaData();
            int numerocolumnas=rsMd.getColumnCount();
            DefaultTableModel modelo=new DefaultTableModel(modelodatos,titulos);
            Tabla_Lista.setModel(modelo);

            while(obj.rs.next()){
                Object [] fila= new Object[numerocolumnas];

                for(int y=0; y<numerocolumnas;y++){
                    fila [y]=obj.rs.getObject(y+1);
                }
                modelo.addRow(fila);
            }
        }
        catch(SQLException ex){
            System.out.println("Error al  buscar: "+ex.getMessage());
        }
    }//GEN-LAST:event_Btt_ListarActionPerformed

    private void Btt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_EliminarActionPerformed
        this.eliminar();
    }//GEN-LAST:event_Btt_EliminarActionPerformed

    private void Btt_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ActualizarActionPerformed
        this.Actualizar();
    }//GEN-LAST:event_Btt_ActualizarActionPerformed

    private void Txt_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DireccionKeyTyped
     char c = evt.getKeyChar();
        if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_Txt_DireccionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_Actualizar;
    private javax.swing.JButton Btt_Consultar;
    private javax.swing.JButton Btt_Eliminar;
    private javax.swing.JButton Btt_Ingresar;
    private javax.swing.JButton Btt_Limpiar;
    private javax.swing.JButton Btt_Listar;
    private javax.swing.JTable Tabla_Lista;
    private javax.swing.JTextField Txt_Ciudad;
    private javax.swing.JTextField Txt_Direccion;
    private javax.swing.JTextField Txt_Documento;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Telefono;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void gurdar_datos_cliente()
{
    obj.Guardar_cliente(Integer.parseInt(Txt_Documento.getText()),Txt_Nombre.getText(), Txt_Direccion.getText(), Txt_Ciudad.getText(), Txt_Telefono.getText());
   JOptionPane.showMessageDialog(null,"DATOS ALMACENADOS CORRECTAMENTE","GUARDAR",JOptionPane.INFORMATION_MESSAGE);
   this.limpiar();
}
    
public void buscar()
 {
 try
 {
 obj.Buscar(Integer.parseInt(Txt_Documento.getText()));
  if(obj.datos.next()==true)
            {
            Txt_Nombre.setText(obj.datos.getString(2));
            Txt_Direccion.setText(obj.datos.getString(3));
            Txt_Ciudad.setText(obj.datos.getString(4));
            Txt_Telefono.setText(obj.datos.getString(5));
            
         
         }
         else
         {
            JOptionPane.showMessageDialog(null,"el registro no existe", "EMPLEADO",  JOptionPane.ERROR_MESSAGE); 
            this.limpiar();
            Txt_Documento.setText("");
            Txt_Documento.grabFocus();
         }
        }
         catch(Exception ex)
         {
             System.out.println("ERROR AL BUSCAR"+ex.getMessage());
         }   
    }
       
    public void Actualizar()
    {
        obj.Modificar_Cliente(Integer.parseInt(Txt_Documento.getText()),Txt_Nombre.getText(),Txt_Direccion.getText(),Txt_Ciudad.getText(), Txt_Telefono.getText());
        this.limpiar();
    }
     
    public void eliminar()
    {
      int  a = JOptionPane.showConfirmDialog(null,"Desea Eliminar los datos?","SISTEMA",0,1);
      if (a==0) 
      { 
        obj.Eliminar(Integer.parseInt(Txt_Documento.getText()));
        JOptionPane.showMessageDialog(null,"El registro fue eliminado","EMPLEADO", JOptionPane.INFORMATION_MESSAGE);  
        this.limpiar();
      }
    
    
    }
    
    public void limpiar()
    {
        Txt_Documento.setText("");
        Txt_Nombre.setText("");
        Txt_Direccion.setText("");
        Txt_Ciudad.setText("");
        Txt_Telefono.setText("");
        
        Tabla_Lista.setModel(new DefaultTableModel());
      
              
     }
}
