/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Class_Ingreso_Taller;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;



/**
 *
 * @author JHON SANCHEZ
 *         YEISON NORIEGA 
 *         ADSI 600128
 */
public class JInternalFrame_IngresoTaller extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame_IngresoTaller
     */
     Class_Ingreso_Taller obj=new Class_Ingreso_Taller();
    public JInternalFrame_IngresoTaller() {
        initComponents();
        setLocation(0, 0);
       // Txt_Fecha.setText(FechaActual());
        
        
        Txt_Fecha.enable(false);
        
        comboxveh.addItem("Seleccione...");
        this.llenarCombo();
         comboxveh.grabFocus();//
         Txt_Placa.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Placa = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Txt_Fecha = new javax.swing.JTextField();
        comboxveh = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Txt_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane1.setLayer(Txt_Fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboxveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxvehActionPerformed(evt);
            }
        });

        jButton1.setText("REGISTRAR INGRESO DE VEHICULO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Seleccione la placa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Fecha");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Prorigger Garage Azul50_.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(comboxveh, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxveh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PlacaActionPerformed

    private void comboxvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxvehActionPerformed
        if(obj.datos!=null)
        {
            //  this.llenarCombo();
            this.mostrarCombo();
        }
    }//GEN-LAST:event_comboxvehActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.GuardarIngresoTaller();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_Fecha;
    private javax.swing.JTextField Txt_Placa;
    private javax.swing.JComboBox comboxveh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

 public void llenarCombo()
    {
        try
        {
            obj.listar_combo_ingreso();
            while(obj.datos.next())
            {
                this.comboxveh.addItem(obj.datos.getString(1));
            }
        }
        catch(Exception ex)
        {
            System.out.println("Error al Cargar los Datos" + ex.getMessage());
        }
    }
    public void mostrarCombo()
    {
        try
        {
            obj.listar_vehiculo(comboxveh.getSelectedItem().toString());
            if(obj.datos.next()==true)
            {
                Txt_Placa.setText(obj.datos.getString(1));
            }
        }
        catch(Exception ex)
        {
            System.out.println("Error al Cargar"+ex.getMessage());
        }
    }

    public void GuardarIngresoTaller()
    {
        try
        {
            obj.GuardarIngresoTaller(Txt_Fecha.getText(), Txt_Placa.getText());
            JOptionPane.showMessageDialog(null,"Datos Almacenados Correctamente ","Guardar",JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        }
        catch(Exception ex)
        {
            System.out.println("Error al Cargar"+ex.getMessage());
        }
    }
    
    public void limpiar()
    {
        comboxveh.setSelectedItem("Selecc..");
        comboxveh.setSelectedItem("Seleccione...");
        Txt_Placa.setText("");
    }
    
public static String FechaActual()
{
    java.util.Date fecha=new java.util.Date ();
    SimpleDateFormat formatoFecha=new SimpleDateFormat();
    
    return formatoFecha.format(fecha);
}
}
