
package VISTA;

import MODELO.Class_Diagnostico;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
/**
 *
 * @author JHON SANCHEZ
 *         YEISON NORIEGA 
 *         ADSI 600128
 */
public class JInternalFrame_Diagnostico extends javax.swing.JInternalFrame {

      Class_Diagnostico obj=new Class_Diagnostico();
      DateFormat df = DateFormat.getDateInstance();
    public String datos_ingreso,aux="NULL";
    /**
     * Creates new form JInternalFrame_Diagnostico
     */
    public JInternalFrame_Diagnostico() {
        initComponents();
        Txt_Fecha.setText(FechaActual());
        Txt_Fecha.enable(false);
        Txt_Id_Placa.enable(false);
        Combo_Id_placa.addItem("Selecc..");
        this.llenarcombo_Id_Placa();
        Combo_Id_placa.grabFocus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Txt_Fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Combo_Id_placa = new javax.swing.JComboBox();
        Txt_Id_Placa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescrip = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButton1.setText("REGISTRAR DIAGNOSTICO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Seleccione la placa");

        Txt_Fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Txt_Fecha.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Fecha / Hora");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Prorigger Garage Azul50_.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descripcion del diagnostico");

        Combo_Id_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Id_placaActionPerformed(evt);
            }
        });

        Txt_Id_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Id_PlacaActionPerformed(evt);
            }
        });

        TextAreaDescrip.setColumns(20);
        TextAreaDescrip.setRows(5);
        TextAreaDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextAreaDescripKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TextAreaDescrip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Combo_Id_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_Id_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Id_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_Id_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)))
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.guardar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Combo_Id_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Id_placaActionPerformed
        if(obj.datos_ingreso!=null)
        {
            this.MostrarCombo_Placa();
        }
        
    }//GEN-LAST:event_Combo_Id_placaActionPerformed

    private void Txt_Id_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Id_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Id_PlacaActionPerformed

    private void TextAreaDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextAreaDescripKeyTyped
       char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
        else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_TextAreaDescripKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_Id_placa;
    private javax.swing.JTextArea TextAreaDescrip;
    private javax.swing.JTextField Txt_Fecha;
    private javax.swing.JTextField Txt_Id_Placa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
public void llenarcombo_Id_Placa()
    {
        
        try
        {
             Combo_Id_placa.removeAllItems();
           Combo_Id_placa.addItem("Seleccione...");
            obj.listar_combo_placa();
            while(obj.datos_ingreso.next())
            {
                this.Combo_Id_placa.addItem(obj.datos_ingreso.getInt(1));
            }
        }
        catch(Exception exCom)
        {
        System.out.println("error al cargar los datos"+exCom.getMessage());
        }
}

public void MostrarCombo_Placa()
    {
        try
        {
         obj.listar_id_placa(Integer.parseInt(Combo_Id_placa.getSelectedItem().toString()));
        if(obj.datos_ingreso.next()== true)
        {
            Txt_Id_Placa.setText(obj.datos_ingreso.getString(3));
        }
        }
        catch(Exception ex)
        {
            System.out.println("Error al cargar el combo"+ex.getMessage());
        }
}

public void guardar() {

    try
    {
     obj.Guardar(aux,Txt_Id_Placa.getText(),Txt_Fecha.getText(), TextAreaDescrip.getText());
    JOptionPane.showMessageDialog(null,"El registro fue ingresado","DIAGNOSTICO", JOptionPane.INFORMATION_MESSAGE); 
       this.limpiar();
       llenarcombo_Id_Placa();
    }
    catch(Exception ex)
    {
        System.out.println("Error al guardar"+ex.getMessage());
    }
   
        
    
 
        
}
public static String FechaActual()
{
    //Date FechaActual = new Date();
    
    java.util.Date fecha=new java.util.Date ();
    SimpleDateFormat formatoFecha=new SimpleDateFormat();
    String fech = formatoFecha.format(fecha);
    
    return formatoFecha.format(fecha);
          
}
public void limpiar()
    {
        Txt_Id_Placa.setText("");
        
       TextAreaDescrip.setText("");//Limpiar cajas de texto
        Combo_Id_placa.setSelectedItem("Seleccione");//Limpiar comobobox
        
             
     }

}
