/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Class_Recepcion_Vehiculos;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author JHON SANCHEZ
 *         YEISON NORIEGA 
 *         ADSI 600128
 */
public class JInternalFrame_Vehiculo extends javax.swing.JInternalFrame {

     MODELO.Class_Recepcion_Cliente conn=new MODELO.Class_Recepcion_Cliente();
    Class_Recepcion_Vehiculos obj=new Class_Recepcion_Vehiculos();
    /**
     * Creates new form JInternalFrame_Vehiculo
     */
    public int variable;
    
    public JInternalFrame_Vehiculo() {
        initComponents();
       ComboBox_Marca.addItem("Selcc");
        this.listar_marca_vehiculo();
        txt_marca.enable(false);
        //////////////////////////////////////////////////
      ComboBox_ClaseVehiculo.addItem("Selcc");
        this.Listar_clase_vehiculos();
        txt_claseVehiculo.enable(false);
        /////////////////////////////////////////////////
      ComboServicio.addItem("Selcc");
       this.listar_ComboBox_Servicio();
        txt_servicio.enable(false);
//         setLocationRelativeTo(null);        
       Combocliente.addItem("Doc Cliente");
        this.llamar_combo_cliente();
        txt_docCliente.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Txt_Placa = new javax.swing.JTextField();
        Txt_Modelo = new javax.swing.JTextField();
        Txt_Color = new javax.swing.JTextField();
        Txt_Clindraje = new javax.swing.JTextField();
        Txt_Kilometraje = new javax.swing.JTextField();
        Txt_No_Motor = new javax.swing.JTextField();
        Txt_No_Chasis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Combocliente = new javax.swing.JComboBox();
        ComboServicio = new javax.swing.JComboBox();
        ComboBox_ClaseVehiculo = new javax.swing.JComboBox();
        ComboBox_Marca = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        txt_servicio = new javax.swing.JTextField();
        txt_claseVehiculo = new javax.swing.JTextField();
        txt_docCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtArea_EstadoV = new javax.swing.JTextArea();
        BttGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Del Vehiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.setName("Clientes"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Placa");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Marca");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Modelo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Color");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Cilindraje");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Kilometraje");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Clase de Vehiculo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Servicio");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Numero de motor");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Numero chasis");

        Txt_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PlacaActionPerformed(evt);
            }
        });
        Txt_Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_PlacaKeyTyped(evt);
            }
        });

        Txt_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ModeloActionPerformed(evt);
            }
        });
        Txt_Modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_ModeloKeyTyped(evt);
            }
        });

        Txt_Color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_ColorKeyTyped(evt);
            }
        });

        Txt_Clindraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_ClindrajeKeyTyped(evt);
            }
        });

        Txt_Kilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_KilometrajeActionPerformed(evt);
            }
        });
        Txt_Kilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_KilometrajeKeyTyped(evt);
            }
        });

        Txt_No_Motor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_No_MotorKeyTyped(evt);
            }
        });

        Txt_No_Chasis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_No_ChasisKeyTyped(evt);
            }
        });

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Estado de Vehiculo");

        Combocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboclienteActionPerformed(evt);
            }
        });

        ComboServicio.setToolTipText("");
        ComboServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboServicioActionPerformed(evt);
            }
        });

        ComboBox_ClaseVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_ClaseVehiculoActionPerformed(evt);
            }
        });

        ComboBox_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_MarcaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Documento Cliente");

        TxtArea_EstadoV.setColumns(20);
        TxtArea_EstadoV.setRows(5);
        TxtArea_EstadoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtArea_EstadoVKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(TxtArea_EstadoV);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Txt_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_No_Chasis, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(147, 147, 147)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Combocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBox_ClaseVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBox_Marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_servicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txt_claseVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_marca)
                            .addComponent(txt_docCliente)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_No_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGap(37, 37, 37)
                                .addComponent(Txt_Clindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ComboBox_ClaseVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_claseVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txt_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Combocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_docCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Txt_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Txt_No_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Txt_No_Chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Txt_Clindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Txt_Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel19)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        BttGuardar.setText("Guardar");
        BttGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BttGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(11, 11, 11)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttGuardar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PlacaActionPerformed

    private void Txt_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ModeloActionPerformed

    private void Txt_ModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ModeloKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO NUMEROS
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ModeloKeyTyped

    private void Txt_ColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ColorKeyTyped
        char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
        else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_Txt_ColorKeyTyped

    private void Txt_ClindrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ClindrajeKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO NUMEROS
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ClindrajeKeyTyped

    private void Txt_KilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_KilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_KilometrajeActionPerformed

    private void Txt_KilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_KilometrajeKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')
        {
            getToolkit().beep();
            evt.consume();//CODIGO PARA INGRESAR SOLO NUMEROS
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_KilometrajeKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Buscar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboclienteActionPerformed
        if(obj.datos!=null)
        {
            this.mostrar_cliente();}        // TODO add your handling code here:
    }//GEN-LAST:event_ComboclienteActionPerformed

    private void BttGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttGuardarActionPerformed
        this.guardar_datos_vehiculo();
    }//GEN-LAST:event_BttGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.Actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.Eliminar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ComboBox_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_MarcaActionPerformed
       if(obj.datos!=null)
        {
            this.Mostrar_combo_marca();
            
        }  
    }//GEN-LAST:event_ComboBox_MarcaActionPerformed

    private void ComboBox_ClaseVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_ClaseVehiculoActionPerformed
         if(obj.datos!=null)
        {
            this.Mostrar_clases_vehiculo();
            
        } 
    }//GEN-LAST:event_ComboBox_ClaseVehiculoActionPerformed

    private void ComboServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboServicioActionPerformed
         if(obj.datos!=null)
        {
          this.Mostrar_clase_servicio();
        } 
    }//GEN-LAST:event_ComboServicioActionPerformed

    private void Txt_No_MotorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_No_MotorKeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_Txt_No_MotorKeyTyped

    private void Txt_No_ChasisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_No_ChasisKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_Txt_No_ChasisKeyTyped

    private void TxtArea_EstadoVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtArea_EstadoVKeyTyped
          char c = evt.getKeyChar();
        if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_TxtArea_EstadoVKeyTyped

    private void Txt_PlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_PlacaKeyTyped
           char c = evt.getKeyChar();
        if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_Txt_PlacaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttGuardar;
    private javax.swing.JComboBox ComboBox_ClaseVehiculo;
    private javax.swing.JComboBox ComboBox_Marca;
    private javax.swing.JComboBox ComboServicio;
    private javax.swing.JComboBox Combocliente;
    private javax.swing.JTextArea TxtArea_EstadoV;
    private javax.swing.JTextField Txt_Clindraje;
    private javax.swing.JTextField Txt_Color;
    private javax.swing.JTextField Txt_Kilometraje;
    private javax.swing.JTextField Txt_Modelo;
    private javax.swing.JTextField Txt_No_Chasis;
    private javax.swing.JTextField Txt_No_Motor;
    private javax.swing.JTextField Txt_Placa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_claseVehiculo;
    private javax.swing.JTextField txt_docCliente;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_servicio;
    // End of variables declaration//GEN-END:variables

 public void guardar_datos_vehiculo()
  {
      if(Txt_Placa.getText().isEmpty() || 
              ComboBox_ClaseVehiculo.getSelectedItem().toString().equals("Seleccione Clase Vehiculo") || 
              Txt_Modelo.getText().isEmpty() || Txt_Color.getText().isEmpty() || 
              Txt_Clindraje.getText().isEmpty() || 
              ComboServicio.getSelectedItem().toString().equals("Tipo de Servicio") || 
              ComboBox_Marca.getSelectedItem().toString().equals("Seleccione Marca") || 
              Txt_No_Motor.getText().isEmpty() || Txt_No_Chasis.getText().isEmpty() || 
              Txt_Kilometraje.getText().isEmpty() || TxtArea_EstadoV.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(null, "Error no deben quedar campos vacios");
      }
      else
      {
         
          obj.Guardar_Datos_Vehiculo(Txt_Placa.getText(),Integer.parseInt(ComboBox_Marca.getSelectedItem().toString()) ,Integer.parseInt(ComboBox_ClaseVehiculo.getSelectedItem().toString()), Integer.parseInt(ComboServicio.getSelectedItem().toString()), Integer.parseInt(Combocliente.getSelectedItem().toString()),
          Txt_Modelo.getText(), Txt_Color.getText(),Txt_Clindraje.getText(),Txt_No_Motor.getText(),Txt_No_Chasis.getText(),Txt_Kilometraje.getText(),TxtArea_EstadoV.getText(),txt_marca.getText(),txt_claseVehiculo.getText(), txt_servicio.getText(),txt_docCliente.getText());

           if(obj.verificar==true)
           {
               JOptionPane.showMessageDialog(null,"DATOS ALMACENADOS CORRECTAMENTE","GUARDAR",JOptionPane.INFORMATION_MESSAGE);
               this.limpiar();
           }
           else
           {
               JOptionPane.showMessageDialog(null,"NO SE HA GUARDADO","GUARDAR",JOptionPane.INFORMATION_MESSAGE);
           }
      }

  
  }
  
 public void Buscar()
 {
    try
    {
     obj.Buscar(Txt_Placa.getText());
     if(obj.datos.next()==true)
     {
      Txt_Placa.setText(obj.datos.getString(1));
      ComboBox_Marca.addItem(obj.datos.getString(2));
      Txt_Modelo.setText(obj.datos.getString(3));
      Txt_Color.setText(obj.datos.getString(4));
      Txt_Clindraje.setText(obj.datos.getString(5));
      ComboBox_ClaseVehiculo.addItem(obj.datos.getString(6));
      ComboServicio.addItem(obj.datos.getString(7));
      Txt_No_Motor.setText(obj.datos.getString(8));
      Txt_No_Chasis.setText(obj.datos.getString(9));
      Txt_Kilometraje.setText(obj.datos.getString(10));
      TxtArea_EstadoV.setText(obj.datos.getString(11));
      Combocliente.addItem(obj.datos.getString(12));
      //Txt_Cliente.setText(obj.datos.getString(12));
          
     }
     else 
     {
        JOptionPane.showMessageDialog(null,"el registro no existe", "PLACA",  JOptionPane.ERROR_MESSAGE); 
            this.limpiar();
            Txt_Placa.setText("");
            Txt_Placa.grabFocus();   
     }    
    } 
     catch(SQLException | HeadlessException ex)
     {
          System.out.println("error al cargar"+ex.getMessage());
     } 
 }
     public void limpiar()
    {
        Txt_Placa.setText("");
        ComboBox_Marca.setSelectedItem("Seleccione Marca");
        Txt_Modelo.setText("");
        Txt_Color.setText("");
        Txt_Clindraje.setText("");
        ComboBox_ClaseVehiculo.setSelectedItem("Seleccione Clase Vehiculo");
        ComboServicio.setSelectedItem("Tipo de Servicio");
        Txt_No_Motor.setText("");
        Txt_No_Chasis.setText("");
        Txt_Kilometraje.setText("");
        TxtArea_EstadoV.setText("");        
        Combocliente.setSelectedItem("Doc Cliente");
        txt_marca.setText("");
        txt_claseVehiculo.setText("");
        txt_servicio.setText("");
     }
     
public void Eliminar()
     {
      int e = JOptionPane.showConfirmDialog(null, "DESEA ELIMINAR LOS DATOS","SISTEMA",0,1);
      if(e==0)
      {
       obj.Eliminar(Txt_Placa.getText());
       JOptionPane.showMessageDialog(null, "EL REGISTRO FUE ELIMINADO","VEHICULO",JOptionPane.INFORMATION_MESSAGE);
       this.limpiar();
      }
      
     }
  public void Actualizar()
  { 
       obj.Actualizar(Txt_Placa.getText(),ComboBox_Marca.getSelectedItem().toString(), Txt_Modelo.getText(),  Txt_Color.getText(),  
               Txt_Clindraje.getText(),ComboBox_ClaseVehiculo.getSelectedItem().toString() ,ComboServicio.getSelectedItem().toString(), Txt_No_Motor.getText(),  
               Txt_No_Chasis.getText(),  Txt_Kilometraje.getText(), TxtArea_EstadoV.getText(),Combocliente.getSelectedItem().toString());
       this.limpiar();
  }
  public void llamar_combo_cliente()
  {
 try{
     obj.listar_combo_cliente();
     
     while(obj.datos.next())
     {
     this.Combocliente.addItem(obj.datos.getInt(1));
      
     }
 }
catch(Exception ex)
{
    System.out.println("error al cargar"+ex.getMessage());
    }
}

private void mostrar_cliente() 
{
        try{
            obj.listar_cliente(Integer.parseInt(Combocliente.getSelectedItem().toString()));
            
        if(obj.datos.next()==true)
     {
        txt_docCliente.setText(obj.datos.getString(2));
     }
 }
catch( Exception ex)
{
    System.out.println("error al cargar"+ex.getMessage());
    }
    }
///////////////////////////////////////////////////////////////////////////////////
public void listar_marca_vehiculo()//Metodo para listar informacion del jcombobox de la marca del vehiculo
{
    try
    {
        
        obj.Listar_Combo_Marca();
        while(obj.datos.next())
        {
            
            this.ComboBox_Marca.addItem(obj.datos.getInt(1));
            //this.ComboBox_Marca.addItem(obj.datos.getString(2));
           
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error al Cargar"+ex.getMessage());
    }
}

private void Mostrar_combo_marca()//Metodo para listar informacion del jcombobox de la marca del vehiculo
{
    
    try
    {
         obj.Listar_Marca(Integer.parseInt(ComboBox_Marca.getSelectedItem().toString()));
         
        if(obj.datos.next()==true)
        {
            txt_marca.setText(obj.datos.getString(2));
        }
        
    }
    catch(Exception ex)
    {
        System.out.println("Error al Cargar"+ex.getMessage());
    }
}
//*****************************************Termina metodo de listar marcas de vehiculos**********************************************************************

public void Listar_clase_vehiculos()
{
    try
    {
        obj.Listar_combo_clase();
        while(obj.datos.next())
        {
            this.ComboBox_ClaseVehiculo.addItem(obj.datos.getInt(1));
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error al Cargar  listar_clase_vehiculo : "+ex.getMessage());
    }
}

private void Mostrar_clases_vehiculo()
{
    
    try
    {
        obj.Listar_clases(Integer.parseInt(ComboBox_ClaseVehiculo.getSelectedItem().toString()));
        if(obj.datos.next()==true)
        {
            txt_claseVehiculo.setText(obj.datos.getString(2));
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error al Cargar"+ex.getMessage());
    }
}


public void listar_ComboBox_Servicio(){
    
    try
    {
        obj.listar_ComboBox_Servicio();
        while(obj.datos.next())
        {
            this.ComboServicio.addItem(obj.datos.getInt(1));
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error al Cargar tipo de servicio: "+ex.getMessage());
    }
    
}
private void Mostrar_clase_servicio(){
    
    try
    {
        obj.Listar_servicio(Integer.parseInt(ComboServicio.getSelectedItem().toString()));
        if(obj.datos.next()==true)
        {
            //txt_servicio.setText(obj.datos.getString(2));
            txt_servicio.setText(obj.datos.getString(2));
            //txt_claseVehiculo.setText(obj.datos.getString(2));
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error al Cargar"+ex.getMessage());
    }
}

}


