/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.Class_Empleados;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JHON SANCHEZ YEISON NORIEGA ADSI 600128
 */
public class JInternalFrame_Empleados extends javax.swing.JInternalFrame {

	CONTROLADOR.Class_CONEXION conn = new CONTROLADOR.Class_CONEXION();
	Class_Empleados obj = new MODELO.Class_Empleados();

	/**
	 * Creates new form JInternalFrame_Empleados
	 */
	public JInternalFrame_Empleados() {
		initComponents();
		combox_IdUser.addItem("Seleccione Id");
		this.LlenarCombo();
		// this.combox_IdUser.removeAllItems();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Txt_Doc_Empleado = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		Txt_Nom_Empleado = new javax.swing.JTextField();
		Txt_Apell_Empleado = new javax.swing.JTextField();
		jLabelIMAGEN = new javax.swing.JLabel();
		BtnLimpiar = new javax.swing.JButton();
		BtnGuardar = new javax.swing.JButton();
		Txt_Combox_IdUser = new javax.swing.JTextField();
		BtnEliminar = new javax.swing.JButton();
		combox_IdUser = new javax.swing.JComboBox();
		BtnActualizar = new javax.swing.JButton();
		BtnConsultar = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setClosable(true);
		setIconifiable(true);
		setMaximizable(true);
		setResizable(true);

		Txt_Doc_Empleado.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				Txt_Doc_EmpleadoKeyTyped(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Documento Empleado");

		Txt_Nom_Empleado.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_Nom_EmpleadoActionPerformed(evt);
			}
		});

		jLabelIMAGEN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelIMAGEN
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Prorigger Garage Azul50%.png"))); // NOI18N
		jLabelIMAGEN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		BtnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnLimpiar.setText("Limpiar");
		BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnLimpiarActionPerformed(evt);
			}
		});

		BtnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnGuardar.setText("Guardar");
		BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnGuardarActionPerformed(evt);
			}
		});

		Txt_Combox_IdUser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Txt_Combox_IdUserActionPerformed(evt);
			}
		});

		BtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnEliminar.setText("Eliminar");
		BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnEliminarActionPerformed(evt);
			}
		});

		combox_IdUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		combox_IdUser.setForeground(new java.awt.Color(255, 0, 0));
		combox_IdUser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				combox_IdUserActionPerformed(evt);
			}
		});

		BtnActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnActualizar.setText("Actualizar");
		BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnActualizarActionPerformed(evt);
			}
		});

		BtnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnConsultar.setText("Consultar");
		BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnConsultarActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Nombre");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Id Usuario");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("Apellido");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(64, 64, 64).addComponent(jLabelIMAGEN,
								javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7,
												Short.MAX_VALUE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup().addGap(48, 48, 48)
														.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
																88, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(combox_IdUser,
																javax.swing.GroupLayout.PREFERRED_SIZE, 111,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(Txt_Combox_IdUser,
																javax.swing.GroupLayout.PREFERRED_SIZE, 91,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(1, 1, 1))
												.addGroup(layout.createSequentialGroup().addGap(75, 75, 75)
														.addComponent(Txt_Apell_Empleado))))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(Txt_Nom_Empleado).addComponent(Txt_Doc_Empleado,
														javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))
								.addGap(31, 31, 31)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(BtnGuardar, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(BtnConsultar, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(BtnActualizar, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
										.addComponent(BtnEliminar, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(BtnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addContainerGap(45, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap().addComponent(jLabelIMAGEN).addGap(39, 39, 39)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Txt_Doc_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addComponent(BtnGuardar))
				.addGap(20, 20, 20)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(Txt_Nom_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(BtnConsultar).addComponent(jLabel2))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(BtnActualizar)
						.addGroup(layout.createSequentialGroup().addGap(41, 41, 41).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(BtnEliminar)
								.addComponent(Txt_Combox_IdUser, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(combox_IdUser, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel4)
								.addComponent(Txt_Apell_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(18, 18, 18).addComponent(BtnLimpiar).addContainerGap(64, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void Txt_Doc_EmpleadoKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_Txt_Doc_EmpleadoKeyTyped
		char c = evt.getKeyChar();
		if (c < '0' || c > '9') {
			getToolkit().beep();
			evt.consume();
		} // TODO add your handling code here:
	}// GEN-LAST:event_Txt_Doc_EmpleadoKeyTyped

	private void Txt_Nom_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_Nom_EmpleadoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_Txt_Nom_EmpleadoActionPerformed

	private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnLimpiarActionPerformed
		this.limpiar();
	}// GEN-LAST:event_BtnLimpiarActionPerformed

	private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnGuardarActionPerformed
		this.guardar_datos_usuario();
	}// GEN-LAST:event_BtnGuardarActionPerformed

	private void Txt_Combox_IdUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Txt_Combox_IdUserActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_Txt_Combox_IdUserActionPerformed

	private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnEliminarActionPerformed
		this.eliminar(); // TODO add your handling code here:
	}// GEN-LAST:event_BtnEliminarActionPerformed

	private void combox_IdUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_combox_IdUserActionPerformed
		if (obj.datos != null) {
			this.mostrar_combo();
		}
	}// GEN-LAST:event_combox_IdUserActionPerformed

	private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnActualizarActionPerformed
		this.Actualizar();
	}// GEN-LAST:event_BtnActualizarActionPerformed

	private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnConsultarActionPerformed
		this.buscar();
	}// GEN-LAST:event_BtnConsultarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BtnActualizar;
	private javax.swing.JButton BtnConsultar;
	private javax.swing.JButton BtnEliminar;
	private javax.swing.JButton BtnGuardar;
	private javax.swing.JButton BtnLimpiar;
	private javax.swing.JTextField Txt_Apell_Empleado;
	private javax.swing.JTextField Txt_Combox_IdUser;
	private javax.swing.JTextField Txt_Doc_Empleado;
	private javax.swing.JTextField Txt_Nom_Empleado;
	private javax.swing.JComboBox combox_IdUser;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabelIMAGEN;
	// End of variables declaration//GEN-END:variables

	public void guardar_datos_usuario() {
		obj.Guardar_Empleado(Txt_Doc_Empleado.getText(), Txt_Nom_Empleado.getText(), Txt_Apell_Empleado.getText(),
				combox_IdUser.getSelectedItem().toString());

		JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS CORRECTAMENTE", "GUARDAR",
				JOptionPane.INFORMATION_MESSAGE);
		this.limpiar();

	}

	public void limpiar() {
		Txt_Doc_Empleado.setText("");
		Txt_Nom_Empleado.setText("");
		Txt_Apell_Empleado.setText("");

	}

	public void buscar() {
		try {
			obj.Buscar(Txt_Doc_Empleado.getText());
			if (obj.datos.next() == true) {
				Txt_Nom_Empleado.setText(obj.datos.getString(2));
				Txt_Apell_Empleado.setText(obj.datos.getString(3));

			} else {
				JOptionPane.showMessageDialog(null, "el registro no existe", "USUARIO", JOptionPane.ERROR_MESSAGE);
				this.limpiar();
				Txt_Doc_Empleado.setText("");
				Txt_Doc_Empleado.grabFocus();
			}
		} catch (Exception ex) {
			System.out.println("ERROR AL BUSCAR");
		}
	}

	public void Actualizar() {
		obj.Modificar_empleado(Txt_Doc_Empleado.getText(), Txt_Nom_Empleado.getText(), Txt_Apell_Empleado.getText(),
				combox_IdUser.getSelectedItem().toString());
		this.limpiar();
	}

	public void eliminar() {
		int a = JOptionPane.showConfirmDialog(null, "Desea Eliminar los datos?", "SISTEMA", 0, 1);
		if (a == 0) {
			obj.Eliminar(Txt_Doc_Empleado.getText());
			JOptionPane.showMessageDialog(null, "El registro fue eliminado", "EMPLEADO",
					JOptionPane.INFORMATION_MESSAGE);
			this.limpiar();
		}

	}

	public void LlenarCombo() {
		try {
			obj.listar_combo_usuario();
			while (obj.datos.next()) {
				this.combox_IdUser.addItem(obj.datos.getString("Usu_tipo"));
			}
		} catch (Exception ex) {
			System.out.println("Error llenar combo" + ex.getMessage());
		}
	}

	private void mostrar_combo() {
		try {

			obj.listar_usuario(combox_IdUser.getSelectedItem().toString());
			if (obj.datos.next() == true) {
				// Txt_Combox_IdUser.setText(obj.datos.getString("Usu_tipo"));
			}
		} catch (Exception es) {
			System.out.println("error al cargar" + es.getMessage());
		}
	}
}
