/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.ClassRegistroMarcaServicio;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author JHON SANCHEZ
 *         YEISON NORIEGA 
 *         ADSI 600128
 */
public class JInternalFrame_VehiculosMarca extends javax.swing.JInternalFrame {

    MODELO.ClassRegistroMarcaServicio conn = new MODELO.ClassRegistroMarcaServicio();
    ClassRegistroMarcaServicio obj = new ClassRegistroMarcaServicio();
    /**
     * Creates new form JInternalFrame_VehiculosMarca
     */
    public JInternalFrame_VehiculosMarca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonRegistrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Maraca_Vehiculo = new javax.swing.JTextField();
        Txt_Marca_Moto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonRegistr = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Txt_Servicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Txt_tipoVehiculo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Registrar Marca de Vehiculos y Motocicletas");

        ButtonRegistrar.setText("Registrar");
        ButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca de Vehiculo");

        jLabel3.setText("Marca de Motocicleta");

        Txt_Maraca_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Maraca_VehiculoActionPerformed(evt);
            }
        });
        Txt_Maraca_Vehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_Maraca_VehiculoKeyTyped(evt);
            }
        });

        Txt_Marca_Moto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_Marca_MotoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonRegistrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_Marca_Moto, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25)
                                .addComponent(Txt_Maraca_Vehiculo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Maraca_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Marca_Moto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(ButtonRegistrar)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonRegistr.setText("Registrar");
        jButtonRegistr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Registrar Tipo de Servicio del Vehiculo ");

        Txt_Servicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_ServicioKeyTyped(evt);
            }
        });

        jLabel5.setText("Tipo de Servicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistr)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistr)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Txt_tipoVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_tipoVehiculoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Registrar Tipo de  Vehiculo ");

        jLabel7.setText("Tipo de Vehiculo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_Maraca_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Maraca_VehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Maraca_VehiculoActionPerformed

    private void ButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrarActionPerformed
     
        this.GuardarMarca();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRegistrarActionPerformed

    private void jButtonRegistrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrActionPerformed

        this.GuardarTipoServicio();
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
       this.GuardarClaseVehiculo();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Txt_Maraca_VehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Maraca_VehiculoKeyTyped
        char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
        else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Maraca_VehiculoKeyTyped

    private void Txt_Marca_MotoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Marca_MotoKeyTyped
        char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
         else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_Txt_Marca_MotoKeyTyped

    private void Txt_ServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ServicioKeyTyped
      char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
         else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_Txt_ServicioKeyTyped

    private void Txt_tipoVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_tipoVehiculoKeyTyped
        char c = evt.getKeyChar();

        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'!' || c>'.')
            && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();//CODIGO PARA INGRESAR SOLO LETRAS
        } 
         else if(Character.isLowerCase(c))//CODIGO PARA FORZAR LA MAYUSCULAS
        {
            String cadena = (""+c).toUpperCase();
            c=cadena.charAt(0);
            evt.setKeyChar(c);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_Txt_tipoVehiculoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegistrar;
    private javax.swing.JTextField Txt_Maraca_Vehiculo;
    private javax.swing.JTextField Txt_Marca_Moto;
    private javax.swing.JTextField Txt_Servicio;
    private javax.swing.JTextField Txt_tipoVehiculo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonRegistr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

public void GuardarMarca()
{
    try
    {
        if(Txt_Maraca_Vehiculo.getText().isEmpty() || Txt_Marca_Moto.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Error no deben quedar campos vacios");
        }
        else
        {
        obj.GuardarMarca(Txt_Maraca_Vehiculo.getText(), Txt_Marca_Moto.getText());
        JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS CORRECTAMENTE","GUARDAE",JOptionPane.INFORMATION_MESSAGE);
        this.Limpiar();
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error " + ex.getMessage());
    }
}
public void GuardarTipoServicio()
{
    try
    {
        if(Txt_Servicio.getText().isEmpty())
        {
         JOptionPane.showMessageDialog(null, "Error no deben quedar campos vacios");   
        }
        else
        {
        obj.GuardarTipoServicio(Txt_Servicio.getText());
        JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS CORRECTAMENTE","GUARDAE",JOptionPane.INFORMATION_MESSAGE);
        this.Limpiar();
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error " + ex.getMessage());
    }
    
}

public void GuardarClaseVehiculo()
{
    try
    {
        if(Txt_tipoVehiculo.getText().isEmpty())
        {
         JOptionPane.showMessageDialog(null, "Error no deben quedar campos vacios");   
        }
        else
        {
        obj.GuardarClaseVehiculo(Txt_tipoVehiculo.getText());
        JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS CORRECTAMENTE","GUARDAE",JOptionPane.INFORMATION_MESSAGE);
        this.Limpiar();
        }
    }
    catch(Exception ex)
    {
        System.out.println("Error " + ex.getMessage());
    }
}
public void Limpiar()
{
    Txt_Maraca_Vehiculo.setText("");
    Txt_Marca_Moto.setText("");
    Txt_Servicio.setText("");
    Txt_tipoVehiculo.setText("");
    
}
}
