/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package VISTA;

import MODELO.cargar;
//import com.sun.awt.AWTUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author JHON SANCHEZ YEISON NORIEGA ADSI 600128
 */
public final class onix extends javax.swing.JFrame {

	/** Creates new form ventana */
	Timer tim;

	public onix() {
		initComponents();
		setLocationRelativeTo(null);

		JFrame.setDefaultLookAndFeelDecorated(true);
		SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.SaharaSkin");
		// setBounds(0,0,0,0);

	}

	public void iniciar() {
		setLocationRelativeTo(null);
		setBounds(0, 0, 0, 0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jProgressBar1 = new javax.swing.JProgressBar();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		panelNice1 = new org.edisoncor.gui.panel.PanelNice();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setUndecorated(true);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jProgressBar1StateChanged(evt);
			}
		});
		getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 530, 20));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagen-animada.gif"))); // NOI18N
		getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 540, 300));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 510, 20));

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/Prorigger Garage Azul50_.png"))); // NOI18N
		getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 280, 40));

		panelNice1.setBackground(new java.awt.Color(255, 255, 255));
		getContentPane().add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 440));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jProgressBar1StateChanged

	}// GEN-LAST:event_jProgressBar1StateChanged

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		// TODO add your handling code here:

		tim = new Timer(80, new temporizador());
		tim.start();
	}// GEN-LAST:event_formWindowOpened

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(onix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				new onix().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JProgressBar jProgressBar1;
	private org.edisoncor.gui.panel.PanelNice panelNice1;
	// End of variables declaration//GEN-END:variables

	/**
	 * @return the Progreso
	 */
	public javax.swing.JProgressBar getProgreso() {
		return jProgressBar1;
	}

	/**
	 * @param Progreso the Progreso to set
	 */
	public void setProgreso(javax.swing.JProgressBar Progreso) {
		this.jProgressBar1 = Progreso;
	}

	public class temporizador implements ActionListener {
		public void actionPerformed(ActionEvent e) {
			int barra = jProgressBar1.getValue();
			barra++;
			jProgressBar1.setValue(barra);
			if (barra == 10) {
				jLabel2.setText("Ejectando modulos.");
			}
			if (barra == 30) {
				jLabel2.setText("Cargando almacen de datos..");
			}
			if (barra == 50) {
				jLabel2.setText("Verificando conexion con Base de datos..");
			}
			if (barra == 100) {
				JFrame_InicioUsuario log = new JFrame_InicioUsuario();
				log.show();
				dispose();
			}

		}
	}
}
